### PR TITLE
Other bug and modification

### LINKED ISSUE #24: Other bug and modification

### PR DESCRIPTION
**Pull request by Zopiote**

### CODE REVIEW

File: Js/script.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+$('.alert').delay(3000).fadeOut('slow',function() { $(this).remove(); });
+console.log('test');
```
Comment (Zopiote) [inline Js/script.js:2]: Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/Zopiote/P5/pullRequest?prid=8313983)
```suggestion
console.log("test");
```
